name: Auto Aggregate Only

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  run-aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create Firebase Key File
        run: |
          echo '${{ secrets.FIREBASE_KEY_JSON }}' > firebase-key.json

      - name: Build
        working-directory: ./stock-fetcher
        run: dotnet build

      # 新增這一行來還原工具
      - name: Restore dotnet tools
        run: dotnet tool restore

      # 新增此步驟來安裝 Playwright 瀏覽器
      - name: Install Playwright Browsers
        run: dotnet tool run playwright install --with-deps

      - name: Run Aggregation Only
        working-directory: ./stock-fetcher
        run: dotnet run -- aggregate