name: Auto Aggregate Only

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  run-aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create Firebase Key File
        run: |
          # 請把 firebase-key.json 建立在你的專案子資料夾 stock-fetcher 裡面
          echo '${{ secrets.FIREBASE_KEY_JSON }}' > ./stock-fetcher/firebase-key.json

      - name: Build
        working-directory: ./stock-fetcher
        run: dotnet build

      # 新增這一行來還原工具
      - name: Restore dotnet tools
        run: dotnet tool restore
        
      - name: Run Aggregation Only
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        working-directory: ./stock-fetcher
        run: dotnet run -- aggregate