name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # 若主分支名稱為 master，請自行修改
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web' # 僅發佈 web 資料夾的內容
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4